# THIS FILE IS TO GRAVE THE INPUT FROM METADATA FILE AND ECHO THE OUTPUT THROUGH THE GITHUB ENVIRONMENT FILE AND AS LONG AS 
# CREATE A FILTE TO ACCESS THROUGH THE GITHUB ENVIRONMENT

#!/bin/sh -l

result=$(($1 + $2))

echo "result=$result" >> $GITHUB_OUTPUT

echo "output file" > containerOutputFile.txt
